### ISSUE TITLE
Optimize the YAML script

### ISSUE THREAD

**Issue by sestok** [jsmadis/menu-scraper#2]
I'd re-write the YAML script in the below format to be more readable 

```
restaurants:
  - name: Cap
    url: https://www.pivnice-ucapa.cz/denni-menu.php
    selector: "body > main > div.container.main-obsah > div > div > div > div > div > div.listek > div"
    tags: 
      - HW

  - name: Suzies
    url: http://www.suzies.cz/poledni-menu.html
    selector: "#food-grid > div:nth-child(2) > div > div[class^=uk]"
    tags: 
      - HW

  - name: Veroni
    url: https://www.menicka.cz/4921-veroni-coffee--chocolate.html
    selector: "#menicka > div > div.text > div.profile > div.obsah > div.menicka"
    tags: 
      - HW

  - name: Bauman
    url: https://ubaumannu.cz/menu
    selector: "#block-yui_3_17_2_3_1488384401748_8513 > div > p"
    tags: 
      - jsmadis

```
